apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: jeroenvdheuvel/kubernetes-helm-test:webserver
          imagePullPolicy: Always
          name: werkspot-kubernetes-helm-webserver
          ports:
            - containerPort: 8080
