---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-proxy
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: proxy
        chart: {{ template "fullname" . }}
    spec:
      containers:
        - image: jeroenvdheuvel/kubernetes-helm-test:proxy
          imagePullPolicy: Always
          name: werkspot-kubernetes-helm-proxy
          ports:
            - containerPort: 8080

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-webserver
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: webserver
        chart: {{ template "fullname" . }}
    spec:
      containers:
        - image: jeroenvdheuvel/kubernetes-helm-test:webserver
          imagePullPolicy: Always
          name: werkspot-kubernetes-helm-webserver
          ports:
            - containerPort: 8080
