---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: proxy

---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webserver
